Contact.create!([
  {first_name: "Les", last_name: "Considine", email: "considine_les@hotmail.com", phone_number: "720-886-3111 x41860", middle_name: nil, bio: nil},
  {first_name: "Laurena", last_name: "Strosin", email: "laurena.strosin@gmail.com", phone_number: "(632) 167-3117 x58062", middle_name: nil, bio: nil},
  {first_name: "Gustavo", last_name: "Schumm", email: "gustavo_schumm@hotmail.com", phone_number: "202-201-0201", middle_name: nil, bio: nil},
  {first_name: "Cathey", last_name: "Bergnaum", email: "bergnaum_cathey@gmail.com", phone_number: "1-248-142-4547 x2960", middle_name: nil, bio: nil},
  {first_name: "Chang", last_name: "Bednar", email: "chang.bednar@gmail.com", phone_number: "380.895.1769 x437", middle_name: nil, bio: nil},
  {first_name: "Terrie", last_name: "Herzog", email: "terrie.herzog@hotmail.com", phone_number: "308-507-1969 x81921", middle_name: nil, bio: nil},
  {first_name: "Stan", last_name: "Littel", email: "littel.stan@yahoo.com", phone_number: "305-213-5188 x5084", middle_name: nil, bio: nil},
  {first_name: "Raymon", last_name: "Gerlach", email: "gerlach.raymon@yahoo.com", phone_number: "1-917-526-0013 x788", middle_name: nil, bio: nil},
  {first_name: "Bud", last_name: "Buckridge", email: "buckridge_bud@yahoo.com", phone_number: "(210) 918-7935", middle_name: nil, bio: nil},
  {first_name: "Yaeko", last_name: "Lemke", email: "yaeko.lemke@hotmail.com", phone_number: "638.168.6532 x03578", middle_name: nil, bio: nil},
  {first_name: "Ricardo", last_name: "Veum", email: "veum.ricardo@gmail.com", phone_number: "(287) 386-6557", middle_name: nil, bio: nil},
  {first_name: "Trista", last_name: "Balistreri", email: "balistreri_trista@gmail.com", phone_number: "(445) 854-8420 x2704", middle_name: nil, bio: nil},
  {first_name: "Norbert", last_name: "Halvorson", email: "halvorson.norbert@yahoo.com", phone_number: "715.503.6681", middle_name: nil, bio: nil},
  {first_name: "Franklin", last_name: "Keeling", email: "franklin.keeling@hotmail.com", phone_number: "207.039.4547", middle_name: nil, bio: nil},
  {first_name: "Trudi", last_name: "Walsh", email: "trudi.walsh@gmail.com", phone_number: "844-078-2993 x86548", middle_name: nil, bio: nil},
  {first_name: "Hee", last_name: "Bartoletti", email: "bartoletti.hee@hotmail.com", phone_number: "776-029-6898 x8849", middle_name: nil, bio: nil},
  {first_name: "Halley", last_name: "Paucek", email: "paucek.halley@yahoo.com", phone_number: "992.994.6237", middle_name: nil, bio: nil},
  {first_name: "Evan", last_name: "Blick", email: "evan.blick@gmail.com", phone_number: "377-021-7804 x404", middle_name: nil, bio: nil},
  {first_name: "Katlyn", last_name: "Walker", email: "katlyn_walker@hotmail.com", phone_number: "1-666-205-0643 x4067", middle_name: nil, bio: nil},
  {first_name: "Alphonso", last_name: "Beer", email: "beer.alphonso@hotmail.com", phone_number: "530.283.6062 x447", middle_name: nil, bio: nil},
  {first_name: "Sarita", last_name: "Shanahan", email: "sarita_shanahan@gmail.com", phone_number: "820-120-6496 x21907", middle_name: nil, bio: nil},
  {first_name: "Sharyn", last_name: "Windler", email: "windler_sharyn@gmail.com", phone_number: "733-737-2039 x2204", middle_name: nil, bio: nil},
  {first_name: "Tisha", last_name: "Hintz", email: "tisha.hintz@hotmail.com", phone_number: "1-190-519-6703 x6539", middle_name: nil, bio: nil},
  {first_name: "Elijah", last_name: "Stiedemann", email: "stiedemann_elijah@hotmail.com", phone_number: "1-208-899-1851 x1518", middle_name: nil, bio: nil},
  {first_name: "Mollie", last_name: "Grant", email: "grant_mollie@hotmail.com", phone_number: "279.800.9260 x749", middle_name: nil, bio: nil},
  {first_name: "Wiley", last_name: "Kling", email: "wiley.kling@hotmail.com", phone_number: "(741) 029-2900 x675", middle_name: nil, bio: nil},
  {first_name: "Sidney", last_name: "Kessler", email: "kessler.sidney@gmail.com", phone_number: "961-651-5890 x7030", middle_name: nil, bio: nil},
  {first_name: "Irma", last_name: "Daniel", email: "daniel_irma@gmail.com", phone_number: "255.583.6331 x95769", middle_name: nil, bio: nil},
  {first_name: "Monty", last_name: "Runolfsdottir", email: "monty.runolfsdottir@yahoo.com", phone_number: "(479) 996-3237 x6575", middle_name: nil, bio: nil},
  {first_name: "Katheryn", last_name: "Mills", email: "katheryn_mills@hotmail.com", phone_number: "627-225-2711 x070", middle_name: nil, bio: nil},
  {first_name: "Dennis", last_name: "Watsica", email: "watsica.dennis@yahoo.com", phone_number: "(357) 843-7864", middle_name: nil, bio: nil},
  {first_name: "Leonida", last_name: "Oberbrunner", email: "oberbrunner_leonida@yahoo.com", phone_number: "1-168-183-6164", middle_name: nil, bio: nil},
  {first_name: "Valery", last_name: "Zboncak", email: "valery_zboncak@gmail.com", phone_number: "1-255-268-6946 x3045", middle_name: nil, bio: nil},
  {first_name: "Naomi", last_name: "Moore", email: "moore.naomi@yahoo.com", phone_number: "968.586.3000 x52221", middle_name: nil, bio: nil},
  {first_name: "Conrad", last_name: "Jaskolski", email: "conrad.jaskolski@yahoo.com", phone_number: "323.550.1579 x13747", middle_name: nil, bio: nil},
  {first_name: "Kristian", last_name: "Fadel", email: "kristian_fadel@yahoo.com", phone_number: "422.336.7393", middle_name: nil, bio: nil},
  {first_name: "Glenn", last_name: "McDermott", email: "glenn_mcdermott@yahoo.com", phone_number: "870.260.1826 x566", middle_name: nil, bio: nil},
  {first_name: "Quintin", last_name: "Hilpert", email: "hilpert_quintin@hotmail.com", phone_number: "757-903-6775", middle_name: nil, bio: nil},
  {first_name: "Ressie", last_name: "Satterfield", email: "ressie_satterfield@gmail.com", phone_number: "(863) 942-2295 x2017", middle_name: nil, bio: nil},
  {first_name: "Dino", last_name: "Zieme", email: "zieme_dino@hotmail.com", phone_number: "1-140-732-5452", middle_name: nil, bio: nil},
  {first_name: "Ora", last_name: "Hayes", email: "hayes.ora@hotmail.com", phone_number: "646-110-6938 x4242", middle_name: nil, bio: nil},
  {first_name: "Christoper", last_name: "Dare", email: "christoper_dare@gmail.com", phone_number: "(491) 734-1079", middle_name: nil, bio: nil},
  {first_name: "Teddy", last_name: "Langosh", email: "langosh.teddy@gmail.com", phone_number: "862-522-3912 x22500", middle_name: nil, bio: nil},
  {first_name: "Leland", last_name: "Auer", email: "auer_leland@hotmail.com", phone_number: "530.168.3333 x774", middle_name: nil, bio: nil},
  {first_name: "Jimmy", last_name: "Mann", email: "jimmy.mann@hotmail.com", phone_number: "1-289-165-3802", middle_name: nil, bio: nil},
  {first_name: "Jodi", last_name: "Kertzmann", email: "kertzmann.jodi@hotmail.com", phone_number: "(156) 793-0090 x629", middle_name: nil, bio: nil},
  {first_name: "Carmine", last_name: "Ratke", email: "ratke.carmine@hotmail.com", phone_number: "(153) 584-2994 x031", middle_name: nil, bio: nil},
  {first_name: "Emil", last_name: "Marquardt", email: "marquardt_emil@hotmail.com", phone_number: "622.062.6601 x602", middle_name: nil, bio: nil},
  {first_name: "Galen", last_name: "Morar", email: "galen.morar@gmail.com", phone_number: "189-372-2386 x9466", middle_name: nil, bio: nil},
  {first_name: "Murray", last_name: "Hoppe", email: "murray.hoppe@yahoo.com", phone_number: "(178) 936-5409", middle_name: nil, bio: nil},
  {first_name: "Saran", last_name: "Keeling", email: "keeling.saran@gmail.com", phone_number: "1-684-190-7293", middle_name: nil, bio: nil},
  {first_name: "Jeffery", last_name: "Crooks", email: "crooks_jeffery@gmail.com", phone_number: "851.534.3140 x62054", middle_name: nil, bio: nil},
  {first_name: "Theo", last_name: "Tromp", email: "tromp.theo@gmail.com", phone_number: "(215) 163-6022 x8295", middle_name: nil, bio: nil},
  {first_name: "Azzie", last_name: "Mayer", email: "azzie.mayer@yahoo.com", phone_number: "1-544-960-4864 x78451", middle_name: nil, bio: nil},
  {first_name: "Stewart", last_name: "Smith", email: "stewart_smith@gmail.com", phone_number: "1-979-705-7663 x493", middle_name: nil, bio: nil},
  {first_name: "Shauna", last_name: "Gleason", email: "shauna_gleason@yahoo.com", phone_number: "478-391-5604 x15696", middle_name: nil, bio: nil},
  {first_name: "Lesia", last_name: "Bartell", email: "lesia.bartell@yahoo.com", phone_number: "1-297-312-6865 x8572", middle_name: nil, bio: nil},
  {first_name: "Donny", last_name: "Davis", email: "donny_davis@gmail.com", phone_number: "(520) 145-8761 x242", middle_name: nil, bio: nil},
  {first_name: "Lynsey", last_name: "Rogahn", email: "rogahn_lynsey@gmail.com", phone_number: "475-481-4726", middle_name: nil, bio: nil},
  {first_name: "Odis", last_name: "Kirlin", email: "odis_kirlin@yahoo.com", phone_number: "1-645-356-2229 x9956", middle_name: nil, bio: nil},
  {first_name: "Tatyana", last_name: "Conroy", email: "conroy.tatyana@gmail.com", phone_number: "(158) 557-3435", middle_name: nil, bio: nil},
  {first_name: "Shon", last_name: "Boyle", email: "shon.boyle@yahoo.com", phone_number: "1-681-939-5288 x9395", middle_name: nil, bio: nil},
  {first_name: "Jeannine", last_name: "Cruickshank", email: "jeannine_cruickshank@hotmail.com", phone_number: "1-410-581-6898", middle_name: nil, bio: nil},
  {first_name: "Louis", last_name: "Turcotte", email: "turcotte_louis@gmail.com", phone_number: "689-093-0865", middle_name: nil, bio: nil},
  {first_name: "Sammie", last_name: "Reilly", email: "reilly_sammie@gmail.com", phone_number: "1-615-545-6641", middle_name: nil, bio: nil},
  {first_name: "Jeff", last_name: "Balistreri", email: "balistreri.jeff@gmail.com", phone_number: "(715) 356-4885 x08093", middle_name: nil, bio: nil},
  {first_name: "Marylee", last_name: "Heaney", email: "marylee_heaney@yahoo.com", phone_number: "722-979-6610", middle_name: nil, bio: nil},
  {first_name: "Tamala", last_name: "Schmidt", email: "tamala_schmidt@yahoo.com", phone_number: "557.363.1334 x6609", middle_name: nil, bio: nil},
  {first_name: "Ursula", last_name: "Zboncak", email: "ursula_zboncak@gmail.com", phone_number: "610.737.9151 x71371", middle_name: nil, bio: nil},
  {first_name: "Jamika", last_name: "Block", email: "jamika.block@gmail.com", phone_number: "286-333-0737 x77783", middle_name: nil, bio: nil},
  {first_name: "Clemmie", last_name: "Hauck", email: "clemmie_hauck@gmail.com", phone_number: "(572) 801-6476 x5268", middle_name: nil, bio: nil},
  {first_name: "Lelia", last_name: "Bradtke", email: "lelia.bradtke@yahoo.com", phone_number: "(564) 362-7193 x316", middle_name: nil, bio: nil},
  {first_name: "Taisha", last_name: "Jacobi", email: "jacobi.taisha@gmail.com", phone_number: "259.386.6940", middle_name: nil, bio: nil},
  {first_name: "Shera", last_name: "Waelchi", email: "waelchi_shera@hotmail.com", phone_number: "1-917-905-7229 x60364", middle_name: nil, bio: nil},
  {first_name: "Chuck", last_name: "Dickens", email: "dickens_chuck@gmail.com", phone_number: "658.877.9380", middle_name: nil, bio: nil},
  {first_name: "Aileen", last_name: "Fay", email: "fay_aileen@hotmail.com", phone_number: "1-153-747-6798", middle_name: nil, bio: nil},
  {first_name: "Ghislaine", last_name: "Adams", email: "adams.ghislaine@hotmail.com", phone_number: "827-245-8856", middle_name: nil, bio: nil},
  {first_name: "Eric", last_name: "Okuneva", email: "eric.okuneva@gmail.com", phone_number: "366.616.8008 x32551", middle_name: nil, bio: nil},
  {first_name: "Sally", last_name: "Cronin", email: "sally.cronin@yahoo.com", phone_number: "1-112-035-4743 x698", middle_name: nil, bio: nil},
  {first_name: "Adolph", last_name: "Rowe", email: "rowe_adolph@gmail.com", phone_number: "624-948-5299 x8700", middle_name: nil, bio: nil},
  {first_name: "Claribel", last_name: "Fritsch", email: "claribel_fritsch@gmail.com", phone_number: "917-921-6373", middle_name: nil, bio: nil},
  {first_name: "Shavon", last_name: "Corwin", email: "shavon_corwin@yahoo.com", phone_number: "(580) 547-5136 x454", middle_name: nil, bio: nil},
  {first_name: "Charisse", last_name: "Kub", email: "charisse_kub@yahoo.com", phone_number: "276.809.6412 x32719", middle_name: nil, bio: nil},
  {first_name: "Frederick", last_name: "Jacobs", email: "frederick_jacobs@yahoo.com", phone_number: "1-914-006-6449 x93395", middle_name: nil, bio: nil},
  {first_name: "Mathilda", last_name: "Wuckert", email: "wuckert_mathilda@hotmail.com", phone_number: "(335) 654-5838 x581", middle_name: nil, bio: nil},
  {first_name: "Lashell", last_name: "Boyer", email: "boyer_lashell@gmail.com", phone_number: "(672) 557-8681 x285", middle_name: nil, bio: nil},
  {first_name: "Allan", last_name: "Trantow", email: "trantow.allan@yahoo.com", phone_number: "452.852.7457", middle_name: nil, bio: nil},
  {first_name: "Isaias", last_name: "Rogahn", email: "isaias_rogahn@gmail.com", phone_number: "(499) 463-6700", middle_name: nil, bio: nil},
  {first_name: "Stephnie", last_name: "Mueller", email: "stephnie_mueller@hotmail.com", phone_number: "(832) 918-6129 x390", middle_name: nil, bio: nil},
  {first_name: "Raymond", last_name: "Walter", email: "raymond.walter@gmail.com", phone_number: "102.764.0135 x03337", middle_name: nil, bio: nil},
  {first_name: "Carmella", last_name: "Wiegand", email: "wiegand.carmella@hotmail.com", phone_number: "574.753.8538 x0002", middle_name: nil, bio: nil},
  {first_name: "Loreen", last_name: "Waelchi", email: "waelchi_loreen@gmail.com", phone_number: "1-193-626-2458 x706", middle_name: nil, bio: nil},
  {first_name: "Miles", last_name: "O'Hara", email: "hara_o_miles@yahoo.com", phone_number: "886.422.7411", middle_name: nil, bio: nil},
  {first_name: "Cecille", last_name: "Anderson", email: "cecille.anderson@gmail.com", phone_number: "130.807.5734 x5004", middle_name: nil, bio: nil},
  {first_name: "Willard", last_name: "Cruickshank", email: "willard_cruickshank@gmail.com", phone_number: "906-711-7620", middle_name: nil, bio: nil},
  {first_name: "Nona", last_name: "Keebler", email: "nona_keebler@gmail.com", phone_number: "1-512-811-5897", middle_name: nil, bio: nil},
  {first_name: "Toney", last_name: "Muller", email: "toney_muller@yahoo.com", phone_number: "1-795-624-4371 x511", middle_name: nil, bio: nil},
  {first_name: "Cherelle", last_name: "Bogan", email: "bogan.cherelle@gmail.com", phone_number: "1-322-099-3192 x36554", middle_name: nil, bio: nil},
  {first_name: "Quentin", last_name: "Effertz", email: "quentin.effertz@yahoo.com", phone_number: "985.020.5528 x415", middle_name: nil, bio: nil},
  {first_name: "Lezlie", last_name: "Bahringer", email: "bahringer.lezlie@gmail.com", phone_number: "1-932-965-5753", middle_name: nil, bio: nil},
  {first_name: "Danielle", last_name: "Osinski", email: "danielle_osinski@hotmail.com", phone_number: "837.575.4762", middle_name: nil, bio: nil},
  {first_name: "Cassy", last_name: "Hyatt", email: "cassy_hyatt@yahoo.com", phone_number: "1-604-964-5392", middle_name: nil, bio: nil},
  {first_name: "Yuk", last_name: "Spencer", email: "yuk_spencer@gmail.com", phone_number: "(717) 281-2868 x132", middle_name: nil, bio: nil},
  {first_name: "Kathaleen", last_name: "Torphy", email: "torphy.kathaleen@hotmail.com", phone_number: "485-964-7642 x671", middle_name: nil, bio: nil},
  {first_name: "Nona", last_name: "Lehner", email: "nona_lehner@gmail.com", phone_number: "1-666-456-6173", middle_name: nil, bio: nil},
  {first_name: "Dorotha", last_name: "Daniel", email: "daniel.dorotha@gmail.com", phone_number: "1-140-271-8134 x48401", middle_name: nil, bio: nil},
  {first_name: "Carolyn", last_name: "Graham", email: "carolyn_graham@yahoo.com", phone_number: "566-513-3399 x5160", middle_name: nil, bio: nil},
  {first_name: "Jess", last_name: "Sipes", email: "sipes.jess@gmail.com", phone_number: "377.038.2632", middle_name: nil, bio: nil},
  {first_name: "Lecia", last_name: "Koelpin", email: "lecia_koelpin@hotmail.com", phone_number: "(301) 815-3316", middle_name: nil, bio: nil},
  {first_name: "Rocky", last_name: "Deckow", email: "deckow.rocky@gmail.com", phone_number: "957-279-0281 x28633", middle_name: nil, bio: nil},
  {first_name: "August", last_name: "Klein", email: "august.klein@gmail.com", phone_number: "420-223-4750", middle_name: nil, bio: nil},
  {first_name: "Linwood", last_name: "Schmeler", email: "schmeler.linwood@yahoo.com", phone_number: "(933) 032-8568", middle_name: nil, bio: nil},
  {first_name: "Charlyn", last_name: "Rogahn", email: "rogahn.charlyn@hotmail.com", phone_number: "978.111.2641", middle_name: nil, bio: nil},
  {first_name: "Tynisha", last_name: "Hegmann", email: "hegmann.tynisha@hotmail.com", phone_number: "963.461.5043 x68611", middle_name: nil, bio: nil},
  {first_name: "Cruz", last_name: "Willms", email: "cruz.willms@gmail.com", phone_number: "138.427.9446 x6197", middle_name: nil, bio: nil},
  {first_name: "Mose", last_name: "Stehr", email: "mose.stehr@hotmail.com", phone_number: "850-430-8493 x78050", middle_name: nil, bio: nil},
  {first_name: "Winfred", last_name: "Lehner", email: "winfred_lehner@yahoo.com", phone_number: "736-591-3334", middle_name: nil, bio: nil},
  {first_name: "Shante", last_name: "Adams", email: "adams_shante@gmail.com", phone_number: "756-154-6527", middle_name: nil, bio: nil},
  {first_name: "Markus", last_name: "Ernser", email: "ernser_markus@gmail.com", phone_number: "757-828-4636", middle_name: nil, bio: nil},
  {first_name: "Waldo", last_name: "Quitzon", email: "waldo.quitzon@gmail.com", phone_number: "796-235-0855 x4946", middle_name: nil, bio: nil},
  {first_name: "Shawnna", last_name: "Schmeler", email: "shawnna_schmeler@gmail.com", phone_number: "522.764.8374", middle_name: nil, bio: nil},
  {first_name: "Felipa", last_name: "Wilkinson", email: "felipa_wilkinson@gmail.com", phone_number: "(344) 050-7976", middle_name: nil, bio: nil},
  {first_name: "Keneth", last_name: "Stroman", email: "stroman.keneth@yahoo.com", phone_number: "713-937-5867 x1122", middle_name: nil, bio: nil},
  {first_name: "Dannie", last_name: "Hyatt", email: "dannie.hyatt@hotmail.com", phone_number: "232-386-4834 x08587", middle_name: nil, bio: nil},
  {first_name: "Frankie", last_name: "Luettgen", email: "luettgen_frankie@yahoo.com", phone_number: "(927) 693-3688", middle_name: nil, bio: nil},
  {first_name: "Leatha", last_name: "Kling", email: "kling.leatha@gmail.com", phone_number: "980-180-9724 x031", middle_name: nil, bio: nil},
  {first_name: "Ezekiel", last_name: "Schiller", email: "ezekiel_schiller@hotmail.com", phone_number: "950.260.0706 x10029", middle_name: nil, bio: nil},
  {first_name: "Wesley", last_name: "O'Connell", email: "connell.wesley.o@gmail.com", phone_number: "940-590-1429 x855", middle_name: nil, bio: nil},
  {first_name: "Gerry", last_name: "Hintz", email: "hintz_gerry@yahoo.com", phone_number: "991.440.6528 x4401", middle_name: nil, bio: nil},
  {first_name: "Mora", last_name: "Kautzer", email: "mora_kautzer@gmail.com", phone_number: "1-520-812-9343 x42963", middle_name: nil, bio: nil},
  {first_name: "Tameika", last_name: "Cole", email: "tameika_cole@yahoo.com", phone_number: "1-751-860-8511", middle_name: nil, bio: nil},
  {first_name: "Damian", last_name: "Crona", email: "crona.damian@gmail.com", phone_number: "540-233-7138", middle_name: nil, bio: nil},
  {first_name: "Quincy", last_name: "Powlowski", email: "powlowski_quincy@gmail.com", phone_number: "(636) 042-5552", middle_name: nil, bio: nil},
  {first_name: "Millard", last_name: "Carter", email: "millard.carter@gmail.com", phone_number: "973.576.4334 x865", middle_name: nil, bio: nil},
  {first_name: "Cris", last_name: "D'Amore", email: "cris_d_amore@hotmail.com", phone_number: "229.911.5082", middle_name: nil, bio: nil},
  {first_name: "Susan", last_name: "Hettinger", email: "susan.hettinger@gmail.com", phone_number: "130.893.6814", middle_name: nil, bio: nil},
  {first_name: "Elicia", last_name: "Kulas", email: "kulas.elicia@hotmail.com", phone_number: "569.443.0292 x711", middle_name: nil, bio: nil},
  {first_name: "Shelton", last_name: "Wintheiser", email: "wintheiser_shelton@gmail.com", phone_number: "843-602-9307 x3123", middle_name: nil, bio: nil},
  {first_name: "Roy", last_name: "Schneider", email: "roy_schneider@gmail.com", phone_number: "542.790.5601", middle_name: nil, bio: nil},
  {first_name: "Sima", last_name: "Monahan", email: "monahan.sima@yahoo.com", phone_number: "409-124-1328 x2572", middle_name: nil, bio: nil},
  {first_name: "Jared", last_name: "Skiles", email: "skiles_jared@hotmail.com", phone_number: "1-750-445-8771", middle_name: nil, bio: nil},
  {first_name: "Keith", last_name: "Kuhlman", email: "kuhlman_keith@gmail.com", phone_number: "(795) 869-9620 x2577", middle_name: nil, bio: nil},
  {first_name: "Nelda", last_name: "Murray", email: "nelda.murray@yahoo.com", phone_number: "152-756-9988 x9842", middle_name: nil, bio: nil},
  {first_name: "Annelle", last_name: "Block", email: "annelle.block@yahoo.com", phone_number: "563-321-1901 x29507", middle_name: nil, bio: nil},
  {first_name: "Jackie", last_name: "McCullough", email: "mccullough.jackie@yahoo.com", phone_number: "(885) 281-9467 x461", middle_name: nil, bio: nil},
  {first_name: "Sonny", last_name: "Bosco", email: "sonny.bosco@yahoo.com", phone_number: "660.233.0861 x7900", middle_name: nil, bio: nil},
  {first_name: "Solomon", last_name: "Turcotte", email: "turcotte.solomon@hotmail.com", phone_number: "740.044.8885", middle_name: nil, bio: nil},
  {first_name: "Angelo", last_name: "Ledner", email: "angelo.ledner@yahoo.com", phone_number: "701-974-3713", middle_name: nil, bio: nil},
  {first_name: "Marc", last_name: "Kling", email: "marc_kling@yahoo.com", phone_number: "1-945-595-5999 x59370", middle_name: nil, bio: nil},
  {first_name: "Judith", last_name: "Frami", email: "judith_frami@yahoo.com", phone_number: "1-912-375-4163 x31790", middle_name: "Miriam", bio: "helloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloohelloheloo"},
  {first_name: "brandon", last_name: "moore", email: "brandon@moore.co", phone_number: "834982398", middle_name: "brandon", bio: "bth my first and middle names are brandon o"}
])



# # 150.times do
# #   first_name = Faker::Name.first_name
# #   last_name = Faker::Name.last_name

# #   contact = Contact.new(
# #     first_name: first_name,
# #     last_name: last_name,
# #     email: Faker::Internet.free_email("#{first_name}.#{last_name}"),
# #     phone_number: Faker::PhoneNumber.phone_number
# #   )
# #   contact.save
# # end



# Group.all

# Contact.all


# ContactGroup.create!(contact_id: 1, group_id: 1)
# ContactGroup.create!(contact_id: 2, group_id: 1)
# ContactGroup.create!(contact_id: 3, group_id: 1)


